### ISSUE TITLE
Consider exporting NFS with root_squash

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-nfs#1]
Some more details in here:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-Securing_NFS-Do_Not_Use_the_no_root_squash_Option.html

**Comment by tiggi** [comment]
Arc probably stops working with root_squash
On 23 Nov 2015 5:06 p.m., Johan Guldmyr <notifications@github.com> wrote:Some more details in here:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-Securing_NFS-Do_Not_Use_the_no_root_squash_Option.html

**Comment by A1ve5** [comment]
Let's keep it like this for now

**Comment by martbhell** [comment]
If someone looks at this in the future, perhaps one could have multiple NFS exports. One to the general compute nodes and a specific one which is only allowed to be mounted by the grid-node.

**Comment by A1ve5** [comment]
do it just for computes

**Comment by martbhell** [comment]
See https://github.com/CSC-IT-Center-for-Science/fgci-ansible/issues/169
